### ISSUE TITLE
Make integration more in line with existing Backstage plugins

### ISSUE THREAD

**Issue by MathewWaltersRVU** [event-catalog/backstage-plugin-eventcatalog#12]
### Use Case

Currently the process is to add service entries to the app config yaml file, this is very un-backstage like.
It would make more sense, and be more in keeping with other backstage plugins, if the mapping was done per component in the catalog info file.

### Proposed Solution

Ideally this would be supported using annotations, something like the below

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "example-component"
  annotations:
    backstage.io/view-url: https://github.com/my%20repo/_git/example-component
    backstage.io/edit-url: https://github.com/my%20repo/_git/example-component?path=/catalog-info.yaml
    backstage.io/source-location: https://github.com/my%20repo/_git/example-component
    eventcatalog.dev/id: example-component-service
    eventcatalog.dev/version: 1.0.0
spec:
  type: service
  owner: group:my-group
  lifecycle: production
```

### Implementation Notes

Using annotations similar to the above.
We could also then check for annotation before we try to render the components.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).
